services:
  bot:
    build:
      context: ./solver-bot
      dockerfile: Dockerfile
    container_name: diffy-bot
    env_file:
      - .env
    environment:
      - SOLVER_API_URL=http://server:8080/api/solver
    depends_on:
      - server
      - database
    networks:
      - net
    restart: unless-stopped

  server:
    build:
      context: ./solver-common
      dockerfile: Dockerfile
    container_name: diffy-bot-server
    env_file:
      - .env
    environment:
      - DB_HOST=database
    ports:
      - "8080:8080"
    volumes:
      - .env:/solver-server/.env:ro
    depends_on:
      - database
    networks:
      - net
    restart: unless-stopped

  database:
    image: postgres:17.5-alpine
    container_name: diffy-bot-database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - net

volumes:
  pgdata:

networks:
  net:
    driver: bridge