logging:
  file:
    name: logs/solver-common.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"

spring:
  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 200