spring:
  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  threads:
    virtual:
      enabled: true

solver:
  max-integration-steps: 1000000
  max-stored-applications-per-user: 5
  application-retention-days: 14
